version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: helpdesk-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: helpdesk_db
    ports:
      - "5433:5432"
    restart: unless-stopped