spring.application.name=helpdesk-api
spring.datasource.url=jdbc:postgresql://localhost:5433/helpdesk_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
api.security.token.secret=${JWT_SECRET}